apiVersion: v1
kind: Service
metadata:
  labels:
    run: customers-service
  name: customers-service
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    run: customers-service
  type: NodePort
