apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: config-server
  template:
    metadata:
      labels:
        run: config-server
    spec:
      containers:
      - name: config-server
        image: config-server:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: config-server
  name: config-server
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    run: config-server
  type: NodePort
