spring:
  #profiles: single
  application:
    name: customers-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 8080

management:
  endpoints:
    web.exposure.include: '*'

service:
  hello-message: ${HELLO_MESSAGE}
  bye-message: ${BYE_MESSAGE}