apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 2
  selector:
    matchLabels:
      run: orders-service
  template:
    metadata:
      labels:
        run: orders-service
    spec:
      containers:
      - name: orders-service
        image: orders-service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: orders-service
  name: orders-service
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    run: orders-service
  type: NodePort
