apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: customers-service
  name: customers-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: customers-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: customers-service
    spec:
      containers:
        - name: customers-service
          image: jloli/customers-service:v0.0.2
          imagePullPolicy: Never
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: /app/config
            - name: HELLO_MESSAGE
              #value: Hey
              valueFrom:
                configMapKeyRef:
                  name: customers-service-cm
                  key: hello.message
            - name: BYE_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: customers-service-secret
                  key: bye.message
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /app/config
              name: customers-service-configvol
          resources: {}
      volumes:
        - name: customers-service-configvol
          configMap:
            name: customers-service-appconfig
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30